#+TITLE: Searching and Sorting Arrays
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: CSC 240 Data Structures Fall 2025
#+OPTIONS: toc:1 num:1 ^:nil:
#+STARTUP: overview hideblocks indent entitiespretty:
* Objectives

1. Introduction to search algorithms
2. Problems solving and program design case study
3. Introduction to sroting algorithms
4. Problems solving and program design case study
5. Sorting and searching ~vector~ objects

* Search algorithms

- What is a search algorithm?
  #+begin_quote
  A *search algorithm* is a method of locating a specific item in a
  larger collection of data.
  #+end_quote

- Example: ~grep~ to search through a list of file name strings.
  #+begin_src bash :results output :exports both
    ls | grep "org"  # find all files with "org" in the name
  #+end_src

  #+RESULTS:
  : 7_arrays_vectors.org
  : 8_search_sort.org
  : 9_pointers.org
  : 9_pointers.org~
  : exercises.org
  : practice.org
  : schedule.org
  : worksheet.org

* Binary search

- *Linear* or *sequential search* uses a single loop to sequentially step
  through an array or ~vector~, starting with the first element. Each
  element is compared with the search value. The search stops when
  either the value is found or the end of the array is encountered.

- *Pseudocode*: =found= is Boolean, and =position= is the =index= of the
  search =value=.
  #+begin_example
  SET found to false
  SET position to -1
  SET index to 0
  WHILE found is false and index < number of elements
      IF list[index] is equal to search value
         found = true
         position = index
      END IF
      ADD 1 to index
  END WHILE
  RETURN position
  #+end_example

- This is the translation of the pseudocode into a function =linearSearch=:
  #+name: linearSearch
  #+begin_src C++ :results none :main no :includes :noweb yes
    //*******************************************************************
    // linearSearch takes a constant integer array of length size and a *
    // search value as arguments & returns its array position, or -1    *
    //*******************************************************************
    int linearSearch(const int arr[], int size, int value) {
      bool found = false;
      int position = -1;
      int index = 0;
      while (index < size && !found) {
        if (arr[index] == value) { // search value found
          found = true;
          position = index;
        }
        index++;
      }
      return position;
    }
    //<<main>>
  #+end_src

* Using linear search

- The example program searches a five-element array =tests= to find a
  score of 100.
  #+name: linearSearch test
  #+begin_src C++ :tangle ../src/linearSearch.cpp :main no :includes :results output :exports both :noweb yes
    #include <iostream>
    using namespace std;

    // Function prototype
    int linearSearch(const int [], int, int);

    // Main program
    int main() {

      // Declare variables.
      const int SIZE = 5;
      int tests[SIZE] = { 87, 75, 98, 100, 82};
      int results;

      // Search the array for 100.
      results = linearSearch(tests, SIZE, 100);

      // If linearSearch returned -1, then 100 was not found.
      if (results == -1)
        cout << "You did not earn 100 points on any test.";
      else {
        // Otherwise results contains the subscript of the first 100 in
        // the array.
        cout << "You earned 100 points on test " << (results + 1);
      }
      return 0;
    }

    // Function definition
    <<linearSearch>>
  #+end_src

#+RESULTS: linearSearch test
: You earned 100 points on test 4

* Efficiency of linear search

- Linear search is an O(N) algorithm, that is, its worst performance
  scales linearly with the number of elements N of the array to be
  searched. On average its performance is N/2 steps.

- Its advantage is that the array does not need to be sorted or stored
  in any particular order.

- This search algorithm should not be used if N is large and speed is
  of the essence.

* NEXT Binary search



* Using binary search

* Efficiency of binary search

* Case study

* Sorting and searching vectors

* Noweb chunks

- Main:
  #+name: main
  #+begin_src C++ :main no :includes :results none  :noweb yes
    int main() {
      return 0;
    }
  #+end_src

* Review questions

* Programming challenges
