* C++ Command-Line Practice Worksheet

This worksheet helps you:
- Tangle C++ code from Org-mode
- Compile it using `g++`
- Run it with and without input files

* Step 1: Write a C++ program
Write a simple program that adds two numbers.

#+begin_src cpp :tangle add.cpp
#include <iostream>
using namespace std;

int main() {
  int a, b;
  cin >> a >> b;
  cout << "Sum is: " << a + b << endl;
  return 0;
}
#+end_src

* Step 2: Tangle the code

- Place your cursor *in the code block above*
- Press =C-c C-v t= to tangle (create the file `add.cpp`)

* Step 3: Check that the file exists

#+begin_src sh
ls -lt add.cpp
#+end_src

#+RESULTS:
: -rw-rw-r-- 1 aletheia aletheia 137 Jul  3 10:42 add.cpp

* Step 4: Compile the program using g++

#+begin_src sh
g++ add.cpp -o add
#+end_src

#+RESULTS:

* Step 5: Run it and type input manually
Type two numbers (e.g., 3 and 7) when prompted.

#+begin_src sh
./add
#+end_src

#+RESULTS:
: Sum is: 1933770571

* Step 6: Create an input file
Manually create a file named `input.txt` in the same folder.  
Put two numbers in it, like this:

#+begin_example
8 11
#+end_example

Now run the program with input redirection:

#+begin_src sh
./add < input.txt
#+end_src

#+RESULTS:

* Step 7: Try modifying the program
Change the code in `add.cpp` to multiply the numbers instead of adding them.  
Then tangle again, recompile, and test it.

* Reflection (optional)
- What do you understand better now?
- What is still confusing?

