#+TITLE: Arrays and Vectors
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: CSC 240 Data Structures Fall 2025
#+OPTIONS: toc:1 num:1 ^:nil:
#+STARTUP: overview hideblocks indent entitiespretty:
* Objectives

- [ ] Array declaration and initialization
- [ ] Array input without loops
- [ ] Stepping through an array with ~for~
- [ ] Running C++ on the command-line with ~make~

* Simple example: Array declaration

- Complete the following program:

  1) Supply the definition for an integer array named =values= of size
     =NUM_ELEMENTS=, and assign the values 100, 200, 300, 400, 500.
  2) Print the values of the array on one line separated by a space.

- Starter code: https://tinyurl.com/array-declaration
  #+begin_src C++ :main no :includes :results output
    // Declare, initialize and print an array of 5 elements
    #include <iostream>
    using namespace std;

    int main()
    {
      // Define size of array NUM_ELEMENTS
      
      // Define int array `values` of size NUM_ELEMENTS and assign
      // 100...500 to the array
      
      // Print the array elements on one line separated by a space
      return 0;
    }
  #+end_src

- Solution: https://onecompiler.com/cpp/43vgaj8dc  
  #+begin_src C++ :main no :includes :results output
    #include <iostream>
    using namespace std;

    int main()
    {
      // Define size of array NUM_ELEMENTS      

      // Define integer array `values` of size NUM_DECLARATOR
      // Assign 100...500 to the array

      // Print the array elements on one line separated by a space

      return 0;
    }
  #+end_src

  #+RESULTS:
  : 100 200 300 400 500 

* Two types of initialization
* PRACTICE Extended example: Declare and Display Product Prices

You need to upload the URL for this practice file to Canvas.

** Scenario

You’ve joined the IT support team at a small e-commerce startup,
QuickCart.  Your first task is to write a simple C++ program that
stores the fixed prices of five featured products.  These prices must
be stored in an array and displayed on a single line for the company
dashboard preview.

** Task

- Complete the program below:
  1. Define an floating-point array named =prices= with size =SIZE=.
  2. Assign the values 10.0 100.0 45.99 30.00 200.00 to the array
     (these represent product prices in dollars).
  3. Print the array elements on one line separated by one space.

- *Expected Output:*
  #+begin_example
  #+RESULTS:
  : 10 100 45.99 30 200
  #+end_example

** Starter Code: [[https://tinyurl.com/array-product-prices][tinyurl.com/array-product-prices]]
#+begin_src C++ :main no :includes :results output
  // Store product prices in an array
  // Author: 

  #include <iostream>
  using namespace std;

  int main()
  {
    // Set SIZE of array
   
    // Define array `prices` and assign product prices
   
    //Print prices on one line
    
    return 0;
  }
#+end_src

** Tip

- Remember to use brace list initialization for the array.
- You can use a loop to print each element with a trailing space.

** Challenges

1) Let a user enter 5 product prices instead of hardcoding them
2) Validate that each input is a positive number.

** Solution

- Code: 
  #+begin_src C++ :main no :includes :results output
    #include <iostream>
    using namespace std;

    int main()
    {
      // set SIZE of array

      // Define array `prices` and assign product prices

      // Print array values on one line separated by one space

      return 0;
    }
  #+end_src

* Inputting array content element-wise

- *Task*: Write a program that asks for the number of hours worked by
  six employees to be entered on the command line. Store the values in
  an array, and then print them on one line separated by one
  space. Constraint: *Do not use loops.*

- *Sample input:* 20 12 40 30 30 15

- *Sample output:*
  #+begin_example
  Enter the hours worked by 6 employees:
  The hours you entered were: 20 12 40 30 30 15
  #+end_example

- *C++ starter code:* [[https://tinyurl.com/employee-hours][tinyurl.com/employee-hours]]
  #+begin_src C++ :noeval :cmdline < input :main no :includes  :results output
    // Program asks for number of hours worked by six employees to be
    // entered on the command-line. Values are stored in an array and
    // printed separated by one space. Do not use loops at all.
    // Author:

    // include header file
    // use std namespace
    // main program
    // define array size declarator NUM_EMPLOYEES
    // define array `hours`
    // ask user for keyboard input
    // get array input from keyboard
    // print output
  #+end_src

- Solution: https://onecompiler.com/cpp/43vgeh56g
  #+begin_src C++ :cmdline < input :main no :includes :results output
    // Program asks for number of hours worked by six employees to be
    // entered on the command-line. Values are stored in an array and
    // printed separated by one space. Do not use loops at all.
    // Author: Marcus Birkenkrahe (pledged)

    // include header file

    // use std namespace

    // main program

      // define array size declarator
      // define array
      // ask user for keyboard input
      // get array input from keyboard
      // print output

    return 0;
    }
  #+end_src

  Input file:
  #+begin_src bash :results output :exports both
    echo "20 12 40 30 30 15" > input
    cat input
  #+end_src

* Stepping through an array

- Change the previous solution to get the keyboard input and generate
  the output using a loop to step through the array.

- Solution: [[https://tinyurl.com/employee-hours-2][tinyurl.com/employee-hours-2]]
  #+begin_src C++ :tangle ~/GitHub/cpp-25/src/hours.cpp :cmdline < input :main no :includes :results output
    // Program asks for number of hours worked by six employees to be
    // entered on the command-line. Values are stored in an array and
    // printed separated by one space. Use for loops.
    // Author: Marcus Birkenkrahe (pledged)    
    // include header file
    #include <iostream>
    // use std namespace
    using namespace std;
    // main program
    int main()
    {
      // define array size declarator

      // define array

      // ask user for keyboard input
      // get array input from keyboard with a loop
      // print output

      return 0;
    }
  #+end_src

  #+begin_src bash :results none :exports both
    echo "20 12 40 30 30 15" > input
  #+end_src

* PRACTICE Running C++ on the command-line (CLI)

1) Open the Google Cloud Shell at ide.cloud.google.com

2) Open the terminal

3) Download the source code from the web:
   #+begin_quote sh
   wget -O hours.cpp tinyurl.com/employee-hours-cli
   #+end_quote

4) Check the file with =cat hours.cpp=

5) Compile the file with =make hours=

6) Run the file with =./hours= and enter 20 12 40 30 30 15

7) Upload screenshot of your terminal with the result to Canvas.


